[apm.project.definition]
name = "p2p-solution"
description = ""

[apm.templates.code]
lambda_template = "utils/templates/lambda.txt"
lambda_cfn_template = "utils/templates/lambda.json"
swagger_template = "utils/templates/api_verbs.json"

[apm.templates.deploy]
project_template = "templates/projectTemplate.json"
api_swagger_template = ["src/api.json", "src/backoffice-api.json", "src/business-platform-api.json"]

[apm.project.folders]
lambdas = "src/lambdas"
layers = "src/layers"
