AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless services for p2p solution

Parameters:
  Environment:
    Type: String
  AppName:
    Type: String
  DeploymentBucket:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  PsycopgLayerDriversLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content: 
        S3Bucket: !Ref DeploymentBucket
        S3Key: deploys/libs/psycopg2.zip
      CompatibleRuntimes:
        - python3.11
      LayerName: !Sub ${Environment}-${AppName}-psycopg-client-layer
  CoreAppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../src/layers/app_core
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

Outputs:
  CoreAppLayer:
    Description: "Core app layer arn"
    Value: !Ref CoreAppLayer
  PsycopgLayer:
    Description: "Pycopg client layer arn"
    Value: !Ref PsycopgLayerDriversLayer